{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "EeDJewzDNtja"
      },
      "outputs": [],
      "source": [
        "# Function to append a new integer to the selected list\n",
        "def List_Add(Int, List):\n",
        "    List.append(Int)\n",
        "    print(f\"Added {Int}. Current list: {List}\")\n",
        "\n",
        "# Function to remove a specific integer from the selected list safely\n",
        "def List_Remove(Int, List):\n",
        "    if len(List) == 0:\n",
        "        print(\"The list is empty.\")\n",
        "    else:\n",
        "        if Int in List:\n",
        "            List.remove(Int)\n",
        "            print(f\"Removed {Int}. Current list: {List}\")\n",
        "        else:\n",
        "            print(\"That score is not in the list.\")\n",
        "\n",
        "# Function to sort the list in descending order (highest to lowest)\n",
        "def Descending_Sort(List):\n",
        "    if len(List) > 0:\n",
        "        List.sort(reverse=True)\n",
        "        print(f\"List sorted in descending order: {List}\")\n",
        "    else:\n",
        "        print(\"The list is empty. Nothing to sort.\")\n",
        "\n",
        "# Function to slice and display only the top 3 scores\n",
        "def Top_Three(List):\n",
        "    if len(List)>= 3:\n",
        "        List.sort(reverse=True)\n",
        "        print(f\"Top 3 Scores: {List[:3]}\")\n",
        "    else:\n",
        "        print(\"You need at least 3 scores in the list to slice the top 3.\")\n",
        "\n",
        "# Function to find the maximum and minimum values in the list\n",
        "def Highest_and_Lowest(List):\n",
        "    if len(List) > 0:\n",
        "        print(f\"Highest Score: {max(List)}\")\n",
        "        print(f\"Lowest Score: {min(List)}\")\n",
        "    else:\n",
        "        print(\"The list is empty.\")\n",
        "\n",
        "# Function to calculate the mathematical average of the list\n",
        "def Average(List):\n",
        "    if len(List) > 0:\n",
        "        average = sum(List) / len(List)\n",
        "        print(f\"Average Score: {average:.2f}\")\n",
        "    else:\n",
        "        print(\"The list is empty.\")\n",
        "\n",
        "# Function to find the very last score (which is the lowest after sorting)\n",
        "def Last_Score(List):\n",
        "    if len(List) > 0:\n",
        "        List.sort(reverse=True)\n",
        "        print(f\"Last Score (Lowest): {List[-1]}\")\n",
        "    else:\n",
        "        print(\"The list is empty.\")\n",
        "\n",
        "# Function to combine the list and the tuple, sort them, and print final stats\n",
        "def All_In_One(List, Tuple):\n",
        "    if len(List) == 0:\n",
        "        print(\"The original list was empty.\")\n",
        "\n",
        "    print(f\"Original scores (before tuple): {List}\")\n",
        "\n",
        "    List.extend(Tuple)\n",
        "    print(f\"New scores tuple: {Tuple}\\n\")\n",
        "\n",
        "    List.sort(reverse=True)\n",
        "\n",
        "    print(f\"Final scores: {List}\")\n",
        "    print(f\"Highest score: {max(List)}\")\n",
        "    print(f\"Lowest score: {min(List)}\")\n",
        "\n",
        "    average = sum(List) /len(List)\n",
        "    print(f\"Average score: {average:.2f}\")\n",
        "\n",
        "    print(f\"Top 3 scores: {List[:3]}\")\n",
        "    print(f\"Last score: {List[-1]}\")\n",
        "    print(\"\\nThank you for using my program.\")\n",
        "\n",
        "# Initialize two empty lists. The second one will become a tuple at the end.\n",
        "Original_Score=[]\n",
        "New_Score_Tuple=[]\n",
        "\n",
        "Name=input(\"Enter your name Sir/Madam: \")\n",
        "\n",
        "print(f\"\\nWelcome {Name}! Both score lists are currently empty. \")\n",
        "\n",
        "Runner= True\n",
        "\n",
        "# Main program loop\n",
        "while Runner:\n",
        "    Operation_Manager= int(input(f\"\"\"\n",
        " Which operation would you like to choose for the lists {Name}?\n",
        " 1. Integer Addition.\n",
        " 2. Integer Removal.\n",
        " 3. Descending List Sorting.\n",
        " 4. List Slicing of the top 3 Scores.\n",
        " 5. Highest and Lowest Scores.\n",
        " 6. Average Score.\n",
        " 7. Last Score.\n",
        " 8. All In One.\n",
        "\n",
        " Enter your choice from (1-8): \"\"\"))\n",
        "\n",
        "    print(\"---------------------------------------------------------------------\")\n",
        "\n",
        "    # Determine which list the user wants to manipulate\n",
        "    if 1 <= Operation_Manager <= 7:\n",
        "        target = input(\"Apply to (1) Original List or (2) New Scores List? : \")\n",
        "        if target == '2':\n",
        "            active_list = New_Score_Tuple\n",
        "        else:\n",
        "            active_list = Original_Score\n",
        "\n",
        "    # Match case for user operations\n",
        "    match Operation_Manager:\n",
        "        case 1:\n",
        "            # Try/Except block to catch invalid non-integer inputs\n",
        "            try:\n",
        "                score_to_add = int(input(\"Enter the integer score to add: \"))\n",
        "                List_Add(score_to_add, active_list)\n",
        "            except ValueError:\n",
        "                print(\"Error: Please enter a valid whole number (integer).\")\n",
        "\n",
        "        case 2:\n",
        "            # Try/Except block to catch invalid non-integer inputs\n",
        "            try:\n",
        "                score_to_remove = int(input(\"Enter the score you want to remove: \"))\n",
        "                List_Remove(score_to_remove, active_list)\n",
        "            except ValueError:\n",
        "                print(\"Error: Please enter a valid whole number (integer).\")\n",
        "\n",
        "        case 3:\n",
        "            Descending_Sort(active_list)\n",
        "\n",
        "        case 4:\n",
        "            Top_Three(active_list)\n",
        "\n",
        "        case 5:\n",
        "            Highest_and_Lowest(active_list)\n",
        "\n",
        "        case 6:\n",
        "            Average(active_list)\n",
        "\n",
        "        case 7:\n",
        "            Last_Score(active_list)\n",
        "\n",
        "        case 8:\n",
        "            # Convert the second list to a tuple before final execution\n",
        "            New_Score_Tuple = tuple(New_Score_Tuple)\n",
        "            All_In_One(Original_Score, New_Score_Tuple)\n",
        "            Runner = False\n",
        "\n",
        "        case _:\n",
        "            print(\"Invalid option. Please choose a number from 1 to 8.\")\n",
        "\n",
        "    print(\"---------------------------------------------------------------------\")"
      ]
    }
  ]
}
